# syntax=docker/dockerfile:1.4
FROM node:24.3.0-alpine

# Set working directory
WORKDIR /app

# Install pnpm 10.13.1 via Corepack
RUN corepack enable && corepack prepare pnpm@10.13.1 --activate

# Copy project files into the container
COPY . .

# Set env to skip confirmation prompts
ENV CI=true

# Install dependencies and approve build scripts
RUN pnpm install && pnpm approve-builds

# Expose the app port
EXPOSE 4321

# Default start command
CMD ["pnpm", "dev", "--host"]
