name: Deploy to AWS via CodeBuild

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.tsx'
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'next.config.js'
      - 'Dockerfile'
      - 'buildspec.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::127111941281:role/davidrstudios-github-oidc-role
          role-session-name: github-actions-session
          aws-region: us-west-2

      - name: Trigger AWS CodeBuild
        run: |
          aws codebuild start-build --project-name davidrstudios-codebuild
